[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run server"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.railway]
name = "purchase-portal"

[[services]]
name = "frontend"
buildCommand = "npm run build"
startCommand = "npm run preview"