services:
  - type: web
    name: purchase-portal-api
    env: node
    buildCommand: npm install
    startCommand: node src/server/index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://admin:admin@rentkar01.fsknlky.mongodb.net/payment_tracker?retryWrites=true&w=majority
      - key: PORT
        value: 8080

  - type: static
    name: purchase-portal-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://purchase-portal-api.onrender.com/api