services:
  # Backend API Service
  - type: web
    name: purchase-portal-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://admin:admin@rentkar01.fsknlky.mongodb.net/payment_tracker?retryWrites=true&w=majority
      - key: PORT
        value: 8080

  # Frontend Service
  - type: static
    name: purchase-portal-frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://purchase-portal-api.onrender.com/api
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html